### ISSUE TITLE
Second save on any form crashes in Edge

### ISSUE THREAD

**Issue by CrispinF** [i7MEDIA/mojoportal#100]
To replicate, use Edge to edit Site Settings (or any other form). On second save, get error, with this in the log:

04 14:20:12,305 ERROR 82.69.43.209 - en-GB - /Admin/SiteSettings.aspx - mojoPortal.Web.Global -  Referrer(none) useragent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134 
System.NullReferenceException: Object reference not set to an instance of an object.
   at mojoPortal.Web.SiteUtils.IsFishyPost(HttpRequest request)
   at mojoPortal.Web.AdminUI.SiteSettingsPage.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at mojoPortal.Web.mojoBasePage.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Short term solution (after inspecting code) is to add an appsetting 

`<add key="CheckFishyReferer" value="false"/>`

But I imagine that could have undesirable consequences??

The above observed in different mojo versions including 2.4.0.9 and 2.6.0.0

**Comment by JosephMDavis** [comment]
This is no longer a problem with Chromium-based Edge so I'm closing this issue. Thanks!
