### ISSUE TITLE
Administration menu not visible

### ISSUE THREAD

**Issue by SinaBina** [i7MEDIA/mojoportal#206]
In clean installation using SQLite data-layer, Administration menu is not visible throwing an exception:

```
2023-06-10 11:20:48,756 ERROR 127.0.0.1 - en-US - /Admin/AdminMenu.aspx - mojoPortal.Web.AdminUI.AdminMenuPage - layout (_AdminMenu) was not found in skin http://localhost:52255/Data/Sites/1/skins/framework/. perhaps it is in a different skin. Error was: System.Web.HttpCompileException (0x80004005): c:\Users\User\Desktop\Mojo\Views\Admin\_AdminMenu.cshtml(14): error CS0219: Warning as Error: The variable 'i' is assigned but its value is never used
   at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at mojoPortal.Web.Components.RazorBridge.RenderPartialToString(String partialName, Object model, ViewDataDictionary viewData, String controller)
   at mojoPortal.Web.AdminUI.AdminMenuPage.PopulateControls() 
```

**Comment by SinaBina** [comment]
The issue is related to the release package not being updated properly. Using the latest source code solves the problem.Release packages need to be updated.

**Comment by JosephMDavis** [comment]
Thank you, @SinaBina. I noticed this yesterday as well and am working on putting new packages together today. Ultimately, it's my fault for not verifying but the Publish feature of Visual Studio didn't properly rebuild the various projects.
