### ISSUE TITLE
Superflexi Accordion issue

### ISSUE THREAD

**Issue by SinaBina** [i7MEDIA/mojoportal#209]
In a clean installation under SQLite data-layer and using superflexi module and Accordion, Tabs are not shown and the following error is logged:

```
2023-06-10 11:51:53,366 ERROR 127.0.0.1 - en-US - /new-page - SuperFlexiUI.WidgetRazor - chosen layout (accordion.cshtml) for _SuperFlexiRazor was not found in skin http://localhost:52255/Data/Sites/1/skins/framework/ or SuperFlexi Solution. Perhaps it is in a different skin or Solution. 
Error was: System.Web.HttpCompileException (0x80004005): c:\Users\User\Desktop\Mojo\Views\SuperFlexi\_SuperFlexiPaging.cshtml(10): error CS1056: Unexpected character '$'
   at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Page_Data_SuperFlexi_Solutions_Accordion_accordion_cshtml.Execute() in c:\Users\User\Desktop\Mojo\Data\SuperFlexi\Solutions\Accordion\accordion.cshtml:line 39
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at mojoPortal.Web.Components.RazorBridge.RenderPartialToString(String partialName, Object model, ViewDataDictionary viewData, String controller)
   at SuperFlexiUI.WidgetRazor.RenderContents(HtmlTextWriter writer) 
```

**Comment by JosephMDavis** [comment]
Thank you, @SinaBina. I noticed this yesterday as well and am working on putting new packages together today. Ultimately, it's my fault for not verifying but the Publish feature of Visual Studio didn't properly rebuild the various projects.
