### ISSUE TITLE
StartIndex cannot be less than zero.

### ISSUE THREAD

**Issue by SinaBina** [i7MEDIA/mojoportal#210]
Under SQLite data-layer in the latest version:
1-Add Superflexi module to a page
2-Setting >Select Accordion
3-Add Item
4-Following error is thrown:

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=StartIndex cannot be less than zero.
Parameter name: startIndex
  Source=mscorlib
  StackTrace:
   at System.String.Substring(Int32 startIndex, Int32 length)
   at mojoPortal.Web.Components.RazorBridge.RenderPartialToString(String partialName, Object model, ViewDataDictionary viewData, String controller) in C:\Users\User\Desktop\mojoportal-master\Web\Controllers\RazorBridge.cs:line 95
   at mojoPortal.Web.Components.RazorBridge.RenderPartialToString(String partialName, Object model, String controller) in C:\Users\User\Desktop\mojoportal-master\Web\Controllers\RazorBridge.cs:line 125
   at SuperFlexiUI.WidgetRazor.RenderContents(HtmlTextWriter writer)
```

![Untitled](https://github.com/i7MEDIA/mojoportal/assets/5496007/55d3fa60-0d35-4620-9246-6f6a8deb4e17)

**Comment by JosephMDavis** [comment]
Fixed by #ca22a008e020bc741fee258b79473a8cdcdf03db

**Comment by JosephMDavis** [comment]
Fixed by ca22a008e020bc741fee258b79473a8cdcdf03db
