### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SinaBina** [i7MEDIA/mojoportal#215]
Hi
In 2.9, deleting Superflexi module from any page throw the following exception in Debug mode:

`2023-07-02 13:24:05,765 ERROR (null) - (null) - (null) - SuperFlexiUI.ModuleConfiguration - System.NullReferenceException: Object reference not set to an instance of an object.
   at mojoPortal.FileSystem.DiskFileSystemProvider.GetVirtualPath(Int32 siteId) in C:\Users\User\Desktop\mojoportal-master\Web\Components\FileSystem\DiskFileSystemProvider.cs:line 135
   at mojoPortal.FileSystem.DiskFileSystemProvider.GetFileSystemPermission(Int32 siteId) in C:\Users\User\Desktop\mojoportal-master\Web\Components\FileSystem\DiskFileSystemProvider.cs:line 78
   at mojoPortal.FileSystem.DiskFileSystemProvider.GetFileSystem(Int32 siteId) in C:\Users\User\Desktop\mojoportal-master\Web\Components\FileSystem\DiskFileSystemProvider.cs:line 43
   at SuperFlexiUI.ModuleConfiguration..ctor(Module module, Boolean reloadDefinitionFromDisk) `

**Comment by JosephMDavis** [comment]
Much of this code has been modified and this issue is not reproduceable using the current codebase. Closing.
